language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: py.test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
env:
  global:
  - ENCRYPTION_LABEL: 1dbde6ec09a5
  - COMMIT_AUTHOR_EMAIL: voidfiles@gmail.com
